In [2]:
!pip install numpy pandas

In [3]:
import numpy as np

In [5]:
A=[1, 2, 3, 4, 5]
type(A)

list

In [7]:
B=np.array([1,2,3,4,5])
type(B) #nd = 'n' arreglos

numpy.ndarray

In [10]:
import sys

#size of array
size_array = sys.getsizeof(1) * len(A)
print("Size array A: ",size_array)

Size array A:  140


In [12]:
#size of numpy array
size_numpy = B.itemsize * B.size
print('Size numpy: ',size_numpy)

Size numpy:  20


In [13]:
# A matrix of 2*5
A= np.array([[1,2,3,4,5],[4,5,7,8,9]])
A

array([[1, 2, 3, 4, 5],
       [4, 5, 7, 8, 9]])

In [14]:
A.shape

(2, 5)

In [24]:
A.flatten().shape   #  flatten nos sirve paraponerlo solo en una dimensión

(10,)

In [25]:
A.reshape(-1,5,1,1,1).shape

(2, 5, 1, 1, 1)

In [17]:
A.reshape(5,2)        #transpuesta de un vector, #

array([[1, 2],
       [3, 4],
       [5, 4],
       [5, 7],
       [8, 9]])

In [18]:
A.reshape(-1,5) #el -1  es como un comodin, porque quiere cumplir el segundo argumento

array([[1, 2, 3, 4, 5],
       [4, 5, 7, 8, 9]])

In [22]:
A.reshape(2,-1)     #el -1 es comocin, para que se cumpla el primer elemento

array([[1, 2, 3, 4, 5],
       [4, 5, 7, 8, 9]])

In [28]:
B = np.arange(0,100)
B.shape

(100,)

In [29]:
B.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
B.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
zeros = np.zeros([10,2])
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
ones = np.ones([10,1])
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [37]:
A = [1,2,3]         #se repite dos veces, lo usa como si fuera string
A * 2

array([2, 4, 6])

In [ ]:
A = np.array([1,2,3])         #con np.array lo vuelte 
A * 2

In [39]:
B = np.array([4,5,6])
A + B

array([5, 7, 9])

In [40]:
C = [1,1,1]         #no se pueden de distintas dimensiones
A + C

array([2, 3, 4])

In [41]:
A * B

array([ 4, 10, 18])